from __future__ import annotations

import struct
from pathlib import Path

import pyarrow as pa
import pytest

from textual_fastdatatable.backend import ArrowBackend
from textual_fastdatatable.wkb import MAX_NESTING_DEPTH, WkbError, wkb_to_wkt

LITTLE_ENDIAN = bytes([1])
BIG_ENDIAN = bytes([0])
POINT = 1
GEOMETRYCOLLECTION = 7
SRID_FLAG = 0x20000000


def _point(*ordinates: float, order: str = "<", type_code: int = POINT) -> bytes:
    """One WKB point, to build the cases that are awkward to spell as hex."""
    prefix = LITTLE_ENDIAN if order == "<" else BIG_ENDIAN
    return (
        prefix
        + struct.pack(f"{order}I", type_code)
        + struct.pack(f"{order}{len(ordinates)}d", *ordinates)
    )


CORPUS_PATH = Path(__file__).parents[1] / "data" / "geoarrow_wkb_corpus.tsv"


def duckdb_corpus() -> list[tuple[str, str]]:
    """(hex WKB, WKT) pairs, generated by duckdb's spatial extension.

    Every geometry type in each of the four dimensionalities, the empties, a
    multi-geometry holding an empty, a nested collection, and the coordinates
    that are awkward to format. Each pair is `ST_GeomFromText(wkt)::blob` and
    `ST_AsText(ST_GeomFromText(wkt))`, so the expected text is duckdb's own.
    """
    lines = CORPUS_PATH.read_text().splitlines()
    pairs = [line.split("\t") for line in lines if not line.startswith("#")]
    return [(hex_wkb, wkt) for hex_wkb, wkt in pairs]


@pytest.mark.parametrize(("hex_wkb", "expected"), duckdb_corpus())
def test_wkt_matches_duckdb(hex_wkb: str, expected: str) -> None:
    assert wkb_to_wkt(bytes.fromhex(hex_wkb)) == expected


def test_big_endian_wkb_reads_the_same_as_little_endian() -> None:
    """duckdb writes little-endian; WKB from elsewhere may not."""
    assert (
        wkb_to_wkt(_point(1.0, 2.0, order=">"))
        == wkb_to_wkt(_point(1.0, 2.0))
        == "POINT (1 2)"
    )


@pytest.mark.parametrize("value", [0.1, 1 / 3, 1e-20, 1e20, -117.93367, 1e16, 5e-324])
def test_a_coordinate_is_the_shortest_text_that_round_trips(value: float) -> None:
    """As duckdb's double-to-text is, so that the two agree on every value."""
    ordinate = wkb_to_wkt(_point(value, value)).removeprefix("POINT (").split(" ")[0]
    assert float(ordinate) == value


@pytest.mark.parametrize(
    "data",
    [
        pytest.param(b"", id="no bytes at all"),
        pytest.param(bytes([2]) + struct.pack("<I", POINT), id="bad byte order"),
        pytest.param(LITTLE_ENDIAN + struct.pack("<I", 99), id="bad geometry type"),
        pytest.param(LITTLE_ENDIAN + struct.pack("<I", 4001), id="bad dimensions"),
        pytest.param(LITTLE_ENDIAN + struct.pack("<I", POINT), id="point, no coords"),
        pytest.param(
            LITTLE_ENDIAN + struct.pack("<I", POINT) + struct.pack("<d", 1.0),
            id="point, one coord",
        ),
        pytest.param(_point(1.0, 2.0) + b"extra", id="trailing bytes"),
    ],
)
def test_wkb_that_is_not_a_geometry_raises(data: bytes) -> None:
    with pytest.raises(WkbError):
        wkb_to_wkt(data)


def test_an_srid_is_read_past_rather_than_spelled() -> None:
    """EWKB puts an SRID after the type code; WKT has nowhere to put it."""
    ewkb = (
        LITTLE_ENDIAN
        + struct.pack("<I", POINT | SRID_FLAG)
        + struct.pack("<I", 4326)
        + struct.pack("<dd", 1.0, 2.0)
    )
    assert wkb_to_wkt(ewkb) == "POINT (1 2)"


def _nested_collections(levels: int) -> bytes:
    """A point wrapped in `levels` GEOMETRYCOLLECTIONs."""
    blob = _point(0.0, 0.0)
    for _ in range(levels):
        blob = LITTLE_ENDIAN + struct.pack("<II", GEOMETRYCOLLECTION, 1) + blob
    return blob


def test_nesting_up_to_the_limit_reads() -> None:
    wkt = wkb_to_wkt(_nested_collections(MAX_NESTING_DEPTH - 1))

    assert wkt.count("GEOMETRYCOLLECTION") == MAX_NESTING_DEPTH - 1
    assert wkt.endswith("POINT (0 0)" + ")" * (MAX_NESTING_DEPTH - 1))


def test_nesting_past_the_limit_is_not_a_geometry() -> None:
    """A WkbError, not a RecursionError: bytes that do not decode as a geometry
    have to reach the caller as that, so a cell can fall back to the blob."""
    with pytest.raises(WkbError, match="nests deeper"):
        wkb_to_wkt(_nested_collections(MAX_NESTING_DEPTH))


def test_a_deeply_nested_geometry_column_renders_as_its_bytes() -> None:
    """The whole path: ~18KB of nested collections used to raise RecursionError
    out of `as_py` and take the widget down."""
    blob = _nested_collections(2000)
    field = pa.field(
        "geom", pa.binary(), metadata={b"ARROW:extension:name": b"geoarrow.wkb"}
    )
    column = pa.array([blob], type=pa.binary())
    assert isinstance(column, pa.Array)
    data = pa.Table.from_arrays([column], schema=pa.schema([field]))

    assert ArrowBackend(data).get_column_at(0) == [blob]
